IStitch/Controllers/ServiceOrderController.cs
using IStitch.Data;
using IStitch.GetSer;
using IStitch.Interface;
using IStitch.Models;
using IStitch.Repository;
using IStitch.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IStitch.Controllers
{
    public class ServiceOrderController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IServiceTypeRepository _serviceTypeRepository;
        private readonly IServiceRepository _serviceRepository;
        private readonly IUserRepository _userRepository;
        private readonly ICustomerItemRepository _customerItemRepository;

        public ServiceOrderController(ILogger<HomeController> logger, IServiceTypeRepository serviceTypeRepository,
            IServiceRepository serviceRepoository, IUserRepository userRepository,
            ICustomerItemRepository customerItemRepository, IHttpContextAccessor httpContextAccessor) 
        { 
            _logger = logger;
            _serviceTypeRepository = serviceTypeRepository;
            _serviceRepository = serviceRepoository;
            _httpContextAccessor = httpContextAccessor;
            _userRepository = userRepository;
            _customerItemRepository = customerItemRepository;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            //var curUserId = _httpContextAccessor.HttpContext.User.GetUserid();
            IEnumerable<ServiceType> serviceType = await _serviceTypeRepository.GetAll();
            CustomerItemViewModel customerItemViewModel = new CustomerItemViewModel
            {
                ServicesTypeCategoryList = serviceType,
                PickUpDate = DateTime.Today.AddDays(2)
            };
            return View(customerItemViewModel);
        }

        [HttpPost]
        //gets the services based of servicetype?
        public async Task<IActionResult> GetServicesByCategory(string Category)
        {
            _logger.LogInformation("ITS HERERERERR: " + Category);
            IEnumerable<Service> services = await _serviceRepository.GetAllWithCategory(Category);
            CustomerItemViewModel customerItemViewModel = new CustomerItemViewModel
            {
                ServiceNameList = services
            };
            return PartialView("_ServiceDropdownPartial", customerItemViewModel);
        }

        //creates the actual serviceOrder
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CustomerItemViewModel item)
        {
            var ser = await _serviceRepository.GetByName(item.SerName);
            var customer = await _userRepository.GetByPhoneNumber(item.PhoneNumber);
            CustomerItems customerItems = new CustomerItems()
            {
                SerName = item.SerName,
                Category = item.CategoryName,
                Service = ser,
                PickUpDate = item.PickUpDate,
                CustomerId = customer.Id,
                ItemDescription = item.ItemDescription
            };

            _customerItemRepository.Add(customerItems);

            return RedirectToAction("Create");
        }

        //get all services related to a customer
        public async Task<IActionResult> getServiceOrderByUser()
        {
            return View();
        }

        //update the list
        [HttpPost]
        public async Task<IActionResult> getCustomerServices(string phoneNumber)
        {
            var customer = await _userRepository.GetByPhoneNumber(phoneNumber);
            IEnumerable<CustomerItems> items = await _customerItemRepository.GetAllWithCustomerId(customer.Id);

            ViewData["CustomerName"] = customer.fName;

            return PartialView("_itemList", items);
        }
    }
}

IStitch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IStitch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IStitch.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-navbar border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IStitch</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ServiceOrder" asp-action="Create">Create Service Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ServiceOrder" asp-action="getServiceOrderByUser"> Get Customer Orders</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item ms-auto">
                                <form asp-area="" asp-controller="Account" asp-action="Logout">
                                    <button class="btn btn-outline-danger">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - IStitch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>