IStitch/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace IStitch.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Form()
        {
            return View();
        }
    }
}

IStitch/Controllers/DetailsController.cs
using IStitch.Interface;
using IStitch.Models;
using IStitch.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;

namespace IStitch.Controllers
{
    public class DetailsController : Controller
    {
        private readonly ILogger<DetailsController> _logger;
        private readonly AppDbContext _context;
        private readonly IServiceRepository _serviceRepository;
        public IEnumerable<Service> ServicesList { get; private set; }

        public DetailsController(ILogger<DetailsController> logger, IServiceRepository serviceRepository, AppDbContext context)
        {
            _logger = logger;
            _context = context;
            _serviceRepository = serviceRepository;
        }

        public async Task<IActionResult> Index(string id)
        {

            //ServicesList = _context.Service.Where(S => S.Category == id).ToList();

            IEnumerable<Service> serviceList = await _serviceRepository.GetAllWithCategory(id);

            //foreach (var service in ServicesList)
            //{
            //    _logger.LogInformation("Get Services: " + service.Name);
            //}

            ViewData["Category"] = id;

            return View(serviceList);
        }
    }
}

IStitch/Controllers/HomeController.cs
using IStitch.Models;
using IStitch.Data;
using IStitch.GetSer;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using IStitch.Interface;
using IStitch.Repository;

namespace IStitch.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        //private readonly AppDbContext _context;
        private readonly IServiceTypeRepository _serviceTypeRepository;
        public GetServices Service;
        public IEnumerable<Models.ServiceType> ServicesList { get; private set; }

        public HomeController(ILogger<HomeController> logger, IServiceTypeRepository serviceTypeRepoository, AppDbContext context, GetServices serv)
        {
            _logger = logger;
            //_context = context;
            //Service = serv;
            _serviceTypeRepository = serviceTypeRepoository;
        }

        public async Task<IActionResult> Index()
        {
            //ServicesList = _context.ServiceType.ToList();
            IEnumerable<ServiceType> ServicesList = await _serviceTypeRepository.GetAll();
            return View(ServicesList);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IStitch/Views/Home/Index.cshtml
@model IEnumerable<ServiceType>

@{
    ViewData["Title"] = "Home Page";
}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal">Welcome!</h1>
        <p class="lead font-weight-normal">Small tailoring buisness located in Ottawa Barrhaven.</p>
        <a class="btn btn-outline-secondary" asp-controller="Contact" asp-action="Form">Contact us!</a>
    </div>

    <div class="d-none d-md-block">
        <img src="images\kisspng-sewing-needle-button-buttons-and-needle-vector-5a845d204a1269.5705279815186240323034.png" alt="Description 2" style="max-width:20%;position: absolute;
  right: 10%;
  bottom: 40%;">
    </div>

</div>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var ser in Model)
            {
                <div class="col-md-3">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@ser.Img" alt="@ser.Img">
                        <h2>@ser.Category</h2>
                        <div class="card-body">
                            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Details" asp-action="Index" asp-route-id="@ser.Category" class="btn btn-sm btn-outline-secondary">View</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>